### ISSUE TITLE
Document steps for adding artwork

### ISSUE THREAD

**Issue by amcewen** [mcqn/my-first-pcb#5]
Instructions on basic bitmap converter in Kicad, and DXF import (for basic board outlines); and then Svg2Shenzhen plugin for Inkscape for doing fancier artwork and/or board outlines.

**Comment by amcewen** [comment]
Documentation done, but my test kicad module doesn't have the layers lined up correctly.  Need to try the latest svg2shenzhen release.

**Comment by amcewen** [comment]
Tried the latest svg2shenzhen release, and it still has the problem.  Similarly if I moved the deer's chest onto the F.Cu layer.  It feels more like a problem with the Edge.Cuts layer, as that's quite a way off from the `REF**` text that's the anchor.

Looking at the code, the Edge.Cuts layer is treated differently, which maybe points in the right direction.  Might be worth trying something on both F.SilkS and F.Mask or F.Cu to see if they all line up, to work out if it is just the Edge.Cuts layer going awry.

**Comment by arthurrowland** [comment]
After a successful import of single outline on the Edge.Cuts layer, I found some issue on a file with multiple shapes. Alignment looked spot on but there was no sign of the Edge.Cuts layer - not even in the footprint window preview.

I don't think it was exporting from svg2shenzhen, since that was the only layer that didn't have a file with its name in the .svg2shenzhen-cache folder after I enabled debug mode. (it might have been there without debug anyway, but I hadn't checked).

When I'm in the footprint editor looking to bring it in, the edge.cuts layer is greyed out - presumably because there is no content on that layer:

![screenshot of layers list in kicad, edge cuts and margin layers are not interactive](https://user-images.githubusercontent.com/78351702/127681241-7b2c5f48-5605-4ca3-9839-618f987b3432.png)

The same shape would happily import correctly on the front silkscreen layer, but I couldn't manually move it or add another shape to the edge cuts layer in the footprint editor:

![screenshot of drop down list of available layers](https://user-images.githubusercontent.com/78351702/127682016-ab577c10-85e6-4134-86b0-0feada800d50.png)

I think that's as far as my skill level can get in debugging but hopefully provides some leads.

**Comment by arthurrowland** [comment]
Oh yeah, versions:

**OS**: Windows 10 Pro 10.0.19042, 64 bit
**KiCad**: (5.1.9)-1
**Inkscape**: 1.0 (4035a4fb49, 2020-05-01)
**svg2shenzen**: 0.2.18.7

**Comment by arthurrowland** [comment]
Prompted by the expertise of @concretedog, I resolved my issues by double checking that the shapes were paths, not only strokes, via `Path` -> `Object to Path` and `Path` -> `Stroke to Path`, and then got a blocky shape that was resolved by adding more nodes to the shape. Looks like edge_cuts has different rules for some reason.

![oval shapes in inkscape with many many nodes](https://user-images.githubusercontent.com/78351702/128890838-e6120d51-a908-46bb-bfa8-d2445592c997.png)

![the imported footprint in kicad](https://user-images.githubusercontent.com/78351702/128890802-e3c7f21e-ae31-4629-a7e4-b159c1d2977e.png)

While I was at it I found some related issues on the svg2shenzen repo with [a search](https://github.com/badgeek/svg2shenzhen/issues?q=is%3Aissue+edge):

[The alignment issue resolved by ungrouping](https://github.com/badgeek/svg2shenzhen/issues/72).

[Missing layers resolved through DPI setting](https://github.com/badgeek/svg2shenzhen/issues/130)

@amcewen do you have the file you were having trouble with for me to test?

**Comment by amcewen** [comment]
I've checked the file that I'd had the problem with.  It was still causing problems (without me trying anything new), and the ungrouping trick fixed it.

**Comment by arthurrowland** [comment]
Does that address the totality of this issue or is there more documentation around bitmaps and DXF that could be added?

**Comment by amcewen** [comment]
I think we can leave it with just the Svg2Shenzhen stuff (given we've run the course twice without the DXF and bitmap stuff - and I don't use either of those in practice anyway, always reach for the better Svg2Shenzhen).
